### PR TITLE
Upgraded tabbable to latest version 1.0.6

### PR DESCRIPTION
**Pull request by iandevlin**

### CODE REVIEW

**Comment by davidtheclark** [comment]
@iandevlin: Is there a reason we need to do this? Doesn't semver take care of the patch update?

**Comment by iandevlin** [comment]
@davidtheclark To be honest, I don't know, does it? You would know more about it than I, so if you think it doesn't need to be done, then I believe you!

**Comment by iandevlin** [comment]
It doesn't appear to work for me when I try to update `focus-trap`. The previous version pf `tabbable`is locked into this current release, so yes, I think that this PR is required.

**Comment by davidtheclark** [comment]
@iandevlin: It's not required. If you delete `focus-trap` and reinstall it, the latest tabbable should come with it.

**Comment by iandevlin** [comment]
@davidtheclark I did that, ran `yarn upgrade focus-trap` and it didn't work. It installed version 1.0.5 of `tabbable`.

**Comment by iandevlin** [comment]
Hi, sorry to be a complete and annoying bore, but I would love this to be merged so I can update where I am using it so that it works in Edge and IE11.

**Comment by davidtheclark** [comment]
@iandevlin: I'm pretty sure something is wrong with your package management. There is no reason that a new release with a minor patch should be necessary — this is exactly what semver is for.

**Comment by davidtheclark** [comment]
Yep, just confirmed locally: a fresh install of this module (with either npm or yarn) also installs tabbable 1.0.6.

**Pull request closed without merging**
