### PR TITLE
Add TypeScript type declarations

### PR DESCRIPTION
**Pull request by TedDriggs**
Added per instructions on TS [declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html).

### CODE REVIEW

**Comment by davidtheclark** [comment]
:wave: @TedDriggs. Since I don't use TypeScript myself, I'm not really interested in maintaining the TS declaration files. This is something that TS has solved in other ways, right?

**Comment by TedDriggs** [comment]
@davidtheclark There is the option to register them with the DefinitelyTyped repository, but the consuming package has to know that those types are available from the external type repo.

Are you planning to change the API for the package? If not, then these shouldn't require maintenance. If you are, I'm happy to take on owning any needed updates to the declaration files when you update the docs (just @ me or assign a ticket). Our team is taking a dependency on focus-trap-react so we're motivated to have these stay current.

**Comment by davidtheclark** [comment]
Ok, @TedDriggs — I'll give this a chance. I'll just leave it to TypeScript users to update as needed.

**Comment by davidtheclark** [comment]
@TedDriggs I really made a mess trying to release this morning ... must be groggy ... but I'm pretty sure I got it out in v2.4.2.

**Pull request merged**
